#!/bin/sh

# Cron executable to check for new signal messages and notify
# Cam Webb <https://github.com/camwebb/signal-cli-wrapper>
# This software is released under GNU GPLv3. See LICENSE file.

# Installation: 1) make this script executable
#               2) configure below
#               2) trigger via crontab, e.g.,
#                    0,10,20,30,40,50 * * * *   /home/foo/bin/checksg

# BEGIN CONFIG
source ~/.local/share/signal-cli/scw_config.sh
# END CONFIG

# Construct sed substitution for reading log and ids
SEDSTR="sed -E "
for i in "${!NUM[@]}"
do
    SEDSTR="$SEDSTR -e 's/(\\"${NUM[$i]}")/"$i"/g' "
done

# test to see if you are online
CK=`ping -c 1 google.com 2> /dev/null | grep '1 received'`

if [ -z "$CK" ]
then
    # echo "not online" > /dev/stderr
    exit 1
else
    MSG=`$SG rcv | \
           gawk 'BEGIN{RS="" ; FS="\n"; ORS = ""}
                 {split($1,n," ")}
                 $1 ~ /^Envelope from/ && $4 ~ /^Body/ {
                   print  " " n[3] }' | eval "$SEDSTR" `
fi

if [ -n "$MSG" ]
then
    export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"
    notify-send -u normal -t 36000000 "Signal msg from$MSG"
    sudo /root/bin/msgterm "Signal msg from$MSG"
fi
